use_frameworks!

target 'InstagramSDK_Example', :exclusive => true do
  pod 'InstagramSDK', :path => '../'
end

target 'InstagramSDK_Tests', :exclusive => true do
  pod 'InstagramSDK', :path => '../'

  
end
